[package]
name = "wscat-rs"
version = "1.0.2"
edition = "2024"
license = "MIT"
authors = ["Ed Sweeney <ed@onextent.com>"]
description = "A cli tool for tailing wss websocket streams"
keywords = ["ws", "websocket", "wss"]
documentation = "https://docs.rs/wscat-rs"
repository = "https://github.com/navicore/wscat-rs"

[dependencies]
anyhow            = "1.0"
atty              = "0.2"
clap              = { version = "4", features = ["derive"] }
futures           = "0.3"
http              = "1.3.1"
native-tls        = "0.2"
tokio             = { version = "1", features = ["full"] }
tokio-tungstenite = { version = "0.27", features = ["native-tls", "connect"] }

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.0"
