[package]
name = "wscat-rs"
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["Ed Sweeney <ed@onextent.com>"]
description = "A cli tool for tailing wss websocket streams"
keywords = ["ws", "websocket", "wss"]
documentation = "https://docs.rs/wscat-rs"
repository = "https://github.com/navicore/wscat-rs"

[dependencies]
tokio             = { version = "1", features = ["full"] }
tokio-tungstenite = { version = "0.26", features = ["native-tls", "connect"] }
native-tls        = "0.2"
clap              = { version = "4", features = ["derive"] }
futures           = "0.3"
anyhow            = "1.0"
atty              = "0.2"
