[package]
name = "wscat-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = {version= "4.5.36", features = ["derive"]}
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = { version = "*" }
futures = { version = "*" }
tungstenite = { version = "*" }
anyhow = { version = "*" }

